FROM quay.io/fedora/fedora-toolbox:44

RUN set -euxo pipefail; \
    dnf install -y flatpak-xdg-open; \
    rm -rf /usr/bin/xdg-open; \
    ln -s /usr/bin/flatpak-xdg-open /usr/bin/xdg-open; \
    dnf -y install \
      python3 \
      python3-devel \
      python3-pip \
      python3-setuptools \
      python3-wheel \
      gcc \
      gcc-c++ \
      make \
      openssl-devel \
      libffi-devel \
      zlib-devel cmake @development-tools \
      https://github.com/VSCodium/vscodium/releases/download/1.112.01907/codium-1.112.01907-el8.x86_64.rpm; \
    curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh; \
    chmod +x ./dotnet-install.sh; \
    ./dotnet-install.sh --version latest --runtime aspnetcore; \
    dnf -y clean all; \
    rm -rf /var/cache/dnf; \
    rm -rf ./dotnet-install.sh;

CMD ["/bin/bash"]
